name: test_thuetro
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.11.0
  firebase_core: ^2.19.0
  flutter:
    sdk: flutter
  dropdown_button2: ^2.3.9
  image_picker: ^1.0.4
  firebase_storage: ^11.3.1
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
